// Code generated by goctl. DO NOT EDIT!
// Source: notice.proto

package notice

import (
	pb2 "bcts/app/admin/rpc/types/pb"
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetWebsocketUrlReq = pb2.GetWebsocketUrlReq
	GetWebsocketUrlRsp = pb2.GetWebsocketUrlRsp

	Notice interface {
		GetWebsocketUrl(ctx context.Context, in *GetWebsocketUrlReq, opts ...grpc.CallOption) (*GetWebsocketUrlRsp, error)
	}

	defaultNotice struct {
		cli zrpc.Client
	}
)

func NewNotice(cli zrpc.Client) Notice {
	return &defaultNotice{
		cli: cli,
	}
}

func (m *defaultNotice) GetWebsocketUrl(ctx context.Context, in *GetWebsocketUrlReq, opts ...grpc.CallOption) (*GetWebsocketUrlRsp, error) {
	client := pb2.NewNoticeClient(m.cli.Conn())
	return client.GetWebsocketUrl(ctx, in, opts...)
}
