// Code generated by goctl. DO NOT EDIT!
// Source: api.proto

package server

import (
	"context"

	"bcts/app/hedge/cmd/rpc/internal/logic"
	"bcts/app/hedge/cmd/rpc/internal/svc"
	"bcts/app/hedge/cmd/rpc/types/pb"
)

type HedgeServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedHedgeServer
}

func NewHedgeServer(svcCtx *svc.ServiceContext) *HedgeServer {
	return &HedgeServer{
		svcCtx: svcCtx,
	}
}

func (s *HedgeServer) CreateOrder(ctx context.Context, in *pb.OrderReq) (*pb.OrderRsp, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}
