// Code generated by goctl. DO NOT EDIT!
// Source: idsrv.proto

package server

import (
	"context"

	"exterior-interactor/app/idsrv/rpc/idsrvpb"
	"exterior-interactor/app/idsrv/rpc/internal/logic"
	"exterior-interactor/app/idsrv/rpc/internal/svc"
)

type IdSrvServer struct {
	svcCtx *svc.ServiceContext
}

func NewIdSrvServer(svcCtx *svc.ServiceContext) *IdSrvServer {
	return &IdSrvServer{
		svcCtx: svcCtx,
	}
}

func (s *IdSrvServer) GetId(ctx context.Context, in *idsrvpb.EmptyReq) (*idsrvpb.GetIdRsp, error) {
	l := logic.NewGetIdLogic(ctx, s.svcCtx)
	return l.GetId(in)
}
