// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/shopspring/decimal"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	coinPricesFieldNames          = builder.RawFieldNames(&CoinPrices{})
	coinPricesRows                = strings.Join(coinPricesFieldNames, ",")
	coinPricesRowsExpectAutoSet   = strings.Join(stringx.Remove(coinPricesFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	coinPricesRowsWithPlaceHolder = strings.Join(stringx.Remove(coinPricesFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	coinPricesModel interface {
		Insert(ctx context.Context, data *CoinPrices) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CoinPrices, error)
		Update(ctx context.Context, data *CoinPrices) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCoinPricesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CoinPrices struct {
		Id       int64               `db:"id"`
		CoinUnit sql.NullString      `db:"coin_unit"` // 币种
		Price    decimal.NullDecimal `db:"price"`     // 日出价格
		Created  time.Time           `db:"created"`
		Updated  time.Time           `db:"updated"`
		DateTime sql.NullString      `db:"date_time"` // 日期
	}
)

func newCoinPricesModel(conn sqlx.SqlConn) *defaultCoinPricesModel {
	return &defaultCoinPricesModel{
		conn:  conn,
		table: "`coin_prices`",
	}
}

func (m *defaultCoinPricesModel) Insert(ctx context.Context, data *CoinPrices) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, coinPricesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CoinUnit, data.Price, data.Created, data.Updated, data.DateTime)
	return ret, err
}

func (m *defaultCoinPricesModel) FindOne(ctx context.Context, id int64) (*CoinPrices, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", coinPricesRows, m.table)
	var resp CoinPrices
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCoinPricesModel) Update(ctx context.Context, data *CoinPrices) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, coinPricesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.CoinUnit, data.Price, data.Created, data.Updated, data.DateTime, data.Id)
	return err
}

func (m *defaultCoinPricesModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCoinPricesModel) tableName() string {
	return m.table
}
