// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/shopspring/decimal"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	offlineTradeInputHistoryFieldNames          = builder.RawFieldNames(&OfflineTradeInputHistory{})
	offlineTradeInputHistoryRows                = strings.Join(offlineTradeInputHistoryFieldNames, ",")
	offlineTradeInputHistoryRowsExpectAutoSet   = strings.Join(stringx.Remove(offlineTradeInputHistoryFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	offlineTradeInputHistoryRowsWithPlaceHolder = strings.Join(stringx.Remove(offlineTradeInputHistoryFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheBrokerOfflineTradeInputHistoryIdPrefix = "cache:broker:offlineTradeInputHistory:id:"
)

type (
	offlineTradeInputHistoryModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *OfflineTradeInputHistory) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*OfflineTradeInputHistory, error)
		Update(ctx context.Context, session sqlx.Session, data *OfflineTradeInputHistory) (sql.Result, error)
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultOfflineTradeInputHistoryModel struct {
		sqlc.CachedConn
		table string
	}

	OfflineTradeInputHistory struct {
		Id int64 `db:"id"` // 主键ID

		TradeBusinessNo string `db:"trade_business_no"` // 业务编号

		TradeTime sql.NullTime `db:"trade_time"`

		OfflineTradeId string `db:"offline_trade_id"` // 线下交易ID

		Uid sql.NullInt64 `db:"uid"` // uid

		UserName sql.NullString `db:"user_name"` // 客户账号

		Name sql.NullString `db:"name"` // 姓名

		Symbol sql.NullString `db:"symbol"` // 品种

		Direction sql.NullInt64 `db:"direction"` // 0买 1卖

		Quantity decimal.Decimal `db:"quantity"` // 数量

		Amount decimal.Decimal `db:"amount"` // 金额

		Price decimal.Decimal `db:"price"` // 价格

		Fee decimal.Decimal `db:"fee"` // 手续费

		TradeId sql.NullString `db:"trade_id"` // 内部成交ID

		Remarks sql.NullString `db:"remarks"` // 备注

		Status sql.NullInt64 `db:"status"` // 业务状态 1一次录入 2二次录入

		Operator1 sql.NullString `db:"operator1"` // 操作员1

		Operator2 sql.NullString `db:"operator2"` // 操作员2

		ReviseOperator sql.NullString `db:"revise_operator"` // 修正操作员

		OperateTime sql.NullTime `db:"operate_time"` // 操作时间

		CreateTime sql.NullTime `db:"create_time"` // 创建时间

	}
)

func newOfflineTradeInputHistoryModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultOfflineTradeInputHistoryModel {
	return &defaultOfflineTradeInputHistoryModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`offline_trade_input_history`",
	}
}

func (m *defaultOfflineTradeInputHistoryModel) Insert(ctx context.Context, session sqlx.Session, data *OfflineTradeInputHistory) (sql.Result, error) {
	brokerOfflineTradeInputHistoryIdKey := fmt.Sprintf("%s%v", cacheBrokerOfflineTradeInputHistoryIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, offlineTradeInputHistoryRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.TradeBusinessNo, data.TradeTime, data.OfflineTradeId, data.Uid, data.UserName, data.Name, data.Symbol, data.Direction, data.Quantity, data.Amount, data.Price, data.Fee, data.TradeId, data.Remarks, data.Status, data.Operator1, data.Operator2, data.ReviseOperator, data.OperateTime)
		}
		return conn.ExecCtx(ctx, query, data.TradeBusinessNo, data.TradeTime, data.OfflineTradeId, data.Uid, data.UserName, data.Name, data.Symbol, data.Direction, data.Quantity, data.Amount, data.Price, data.Fee, data.TradeId, data.Remarks, data.Status, data.Operator1, data.Operator2, data.ReviseOperator, data.OperateTime)
	}, brokerOfflineTradeInputHistoryIdKey)
}

func (m *defaultOfflineTradeInputHistoryModel) FindOne(ctx context.Context, id int64) (*OfflineTradeInputHistory, error) {
	brokerOfflineTradeInputHistoryIdKey := fmt.Sprintf("%s%v", cacheBrokerOfflineTradeInputHistoryIdPrefix, id)
	var resp OfflineTradeInputHistory
	err := m.QueryRowCtx(ctx, &resp, brokerOfflineTradeInputHistoryIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", offlineTradeInputHistoryRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOfflineTradeInputHistoryModel) Update(ctx context.Context, session sqlx.Session, data *OfflineTradeInputHistory) (sql.Result, error) {
	brokerOfflineTradeInputHistoryIdKey := fmt.Sprintf("%s%v", cacheBrokerOfflineTradeInputHistoryIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, offlineTradeInputHistoryRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.TradeBusinessNo, data.TradeTime, data.OfflineTradeId, data.Uid, data.UserName, data.Name, data.Symbol, data.Direction, data.Quantity, data.Amount, data.Price, data.Fee, data.TradeId, data.Remarks, data.Status, data.Operator1, data.Operator2, data.ReviseOperator, data.OperateTime, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.TradeBusinessNo, data.TradeTime, data.OfflineTradeId, data.Uid, data.UserName, data.Name, data.Symbol, data.Direction, data.Quantity, data.Amount, data.Price, data.Fee, data.TradeId, data.Remarks, data.Status, data.Operator1, data.Operator2, data.ReviseOperator, data.OperateTime, data.Id)
	}, brokerOfflineTradeInputHistoryIdKey)
}

func (m *defaultOfflineTradeInputHistoryModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	brokerOfflineTradeInputHistoryIdKey := fmt.Sprintf("%s%v", cacheBrokerOfflineTradeInputHistoryIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, brokerOfflineTradeInputHistoryIdKey)
	return err
}

func (m *defaultOfflineTradeInputHistoryModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheBrokerOfflineTradeInputHistoryIdPrefix, primary)
}
func (m *defaultOfflineTradeInputHistoryModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", offlineTradeInputHistoryRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultOfflineTradeInputHistoryModel) tableName() string {
	return m.table
}
