// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userRoleFieldNames          = builder.RawFieldNames(&UserRole{})
	userRoleRows                = strings.Join(userRoleFieldNames, ",")
	userRoleRowsExpectAutoSet   = strings.Join(stringx.Remove(userRoleFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	userRoleRowsWithPlaceHolder = strings.Join(stringx.Remove(userRoleFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	userRoleModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *UserRole) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserRole, error)
		FindOneByUserIdRoleId(ctx context.Context, userId int64, roleId int64) (*UserRole, error)
		Update(ctx context.Context, session sqlx.Session, data *UserRole) (sql.Result, error)
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultUserRoleModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserRole struct {
		Id int64 `db:"id"` // 自增长id

		UserId int64 `db:"user_id"` // user_id

		RoleId int64 `db:"role_id"` // role_id

		LastOperator int64 `db:"last_operator"` //  最后一次操作人,0-表示由程序自动化创建

		Created time.Time `db:"created"` // 创建时间

		Updated time.Time `db:"updated"` // 最近更新时间

	}
)

func newUserRoleModel(conn sqlx.SqlConn) *defaultUserRoleModel {
	return &defaultUserRoleModel{
		conn:  conn,
		table: "`user_role`",
	}
}

func (m *defaultUserRoleModel) Insert(ctx context.Context, session sqlx.Session, data *UserRole) (sql.Result, error) {

	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, userRoleRowsExpectAutoSet)
	if session != nil {
		return session.ExecCtx(ctx, query, data.UserId, data.RoleId, data.LastOperator, data.Created, data.Updated)
	}
	return m.conn.ExecCtx(ctx, query, data.UserId, data.RoleId, data.LastOperator, data.Created, data.Updated)
}

func (m *defaultUserRoleModel) FindOne(ctx context.Context, id int64) (*UserRole, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userRoleRows, m.table)
	var resp UserRole
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserRoleModel) FindOneByUserIdRoleId(ctx context.Context, userId int64, roleId int64) (*UserRole, error) {
	var resp UserRole
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `role_id` = ? limit 1", userRoleRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, roleId)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserRoleModel) Update(ctx context.Context, session sqlx.Session, data *UserRole) (sql.Result, error) {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userRoleRowsWithPlaceHolder)
	if session != nil {
		return session.ExecCtx(ctx, query, data.UserId, data.RoleId, data.LastOperator, data.Created, data.Updated, data.Id)
	}
	return m.conn.ExecCtx(ctx, query, data.UserId, data.RoleId, data.LastOperator, data.Created, data.Updated, data.Id)
}

func (m *defaultUserRoleModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	if session != nil {
		_, err := session.ExecCtx(ctx, query, id)
		return err
	}
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserRoleModel) tableName() string {
	return m.table
}
