// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/shopspring/decimal"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	orderFieldNames          = builder.RawFieldNames(&Order{})
	orderRows                = strings.Join(orderFieldNames, ",")
	orderRowsExpectAutoSet   = strings.Join(stringx.Remove(orderFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	orderRowsWithPlaceHolder = strings.Join(stringx.Remove(orderFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheOrderIdPrefix = "cache:order:id:"
)

type (
	orderModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *Order) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Order, error)
		Update(ctx context.Context, session sqlx.Session, data *Order) (sql.Result, error)
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultOrderModel struct {
		sqlc.CachedConn
		table string
	}

	Order struct {
		Id int64 `db:"id"` // 自增id

		UserId int64 `db:"user_id"` // 用户id

		OrderLocalId string `db:"order_local_id"` // 本地报单编号

		OrderType int64 `db:"order_type"` // 订单类型 1:otc订单 2:聚合交易订单

		OrderMode int64 `db:"order_mode"` // 下单模式 0:按数量询价/下单 1:按金额询价/下单

		OrderPriceType int64 `db:"order_price_type"` // 报单价格条件 1:限价单 2:市价单

		Symbol string `db:"symbol"` // 币对 BTC_USDT

		BaseCurrency string `db:"base_currency"` // 基础币种 USDT

		TargetCurrency string `db:"target_currency"` // 目标币种 BTC

		Direction int64 `db:"direction"` // 0:买 1:卖

		Price decimal.Decimal `db:"price"` // 报单价格

		Volume decimal.Decimal `db:"volume"` // 报单数量

		Amount decimal.Decimal `db:"amount"` // 报单金额, 根据金额下单时用到

		OrderMaker int64 `db:"order_maker"` // 1:taker 2:maker

		TradeVolume decimal.Decimal `db:"trade_volume"` // 已成交数量

		TradeAmount decimal.Decimal `db:"trade_amount"` // 已成交金额(包括手续费)

		FeeKind int64 `db:"fee_kind"` // 订单创建时的手续费类型 1:百分比 2:绝对值

		FeeRate decimal.Decimal `db:"fee_rate"` // 订单创建时的手续费类型

		OrderStatus int64 `db:"order_status"` // 订单状态 0:已发送 1:全部成交 2:部分成交在队列 3:部分成交已撤单 4:撤单

		OrderCreateTime time.Time `db:"order_create_time"` // 订单创建时间

		OrderModifyTime time.Time `db:"order_modify_time"` // 订单修改时间

	}
)

func newOrderModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultOrderModel {
	return &defaultOrderModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`order`",
	}
}

func (m *defaultOrderModel) Insert(ctx context.Context, session sqlx.Session, data *Order) (sql.Result, error) {
	orderIdKey := fmt.Sprintf("%s%v", cacheOrderIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, orderRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.UserId, data.OrderLocalId, data.OrderType, data.OrderMode, data.OrderPriceType, data.Symbol, data.BaseCurrency, data.TargetCurrency, data.Direction, data.Price, data.Volume, data.Amount, data.OrderMaker, data.TradeVolume, data.TradeAmount, data.FeeKind, data.FeeRate, data.OrderStatus, data.OrderCreateTime, data.OrderModifyTime)
		}
		return conn.ExecCtx(ctx, query, data.UserId, data.OrderLocalId, data.OrderType, data.OrderMode, data.OrderPriceType, data.Symbol, data.BaseCurrency, data.TargetCurrency, data.Direction, data.Price, data.Volume, data.Amount, data.OrderMaker, data.TradeVolume, data.TradeAmount, data.FeeKind, data.FeeRate, data.OrderStatus, data.OrderCreateTime, data.OrderModifyTime)
	}, orderIdKey)
}

func (m *defaultOrderModel) FindOne(ctx context.Context, id int64) (*Order, error) {
	orderIdKey := fmt.Sprintf("%s%v", cacheOrderIdPrefix, id)
	var resp Order
	err := m.QueryRowCtx(ctx, &resp, orderIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", orderRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrderModel) Update(ctx context.Context, session sqlx.Session, data *Order) (sql.Result, error) {
	orderIdKey := fmt.Sprintf("%s%v", cacheOrderIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, orderRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.UserId, data.OrderLocalId, data.OrderType, data.OrderMode, data.OrderPriceType, data.Symbol, data.BaseCurrency, data.TargetCurrency, data.Direction, data.Price, data.Volume, data.Amount, data.OrderMaker, data.TradeVolume, data.TradeAmount, data.FeeKind, data.FeeRate, data.OrderStatus, data.OrderCreateTime, data.OrderModifyTime, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.UserId, data.OrderLocalId, data.OrderType, data.OrderMode, data.OrderPriceType, data.Symbol, data.BaseCurrency, data.TargetCurrency, data.Direction, data.Price, data.Volume, data.Amount, data.OrderMaker, data.TradeVolume, data.TradeAmount, data.FeeKind, data.FeeRate, data.OrderStatus, data.OrderCreateTime, data.OrderModifyTime, data.Id)
	}, orderIdKey)
}

func (m *defaultOrderModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	orderIdKey := fmt.Sprintf("%s%v", cacheOrderIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, orderIdKey)
	return err
}

func (m *defaultOrderModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheOrderIdPrefix, primary)
}
func (m *defaultOrderModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", orderRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultOrderModel) tableName() string {
	return m.table
}
