// Code generated by goctl. DO NOT EDIT!
// Source: notice.proto

package server

import (
	"context"

	"market_server/app/notice/api/v1"
	"market_server/app/notice/internal/logic"
	"market_server/app/notice/internal/svc"
)

type NoticeServer struct {
	svcCtx *svc.ServiceContext
	v1.UnimplementedNoticeServer
}

func NewNoticeServer(svcCtx *svc.ServiceContext) *NoticeServer {
	return &NoticeServer{
		svcCtx: svcCtx,
	}
}

func (s *NoticeServer) Send(ctx context.Context, in *v1.NoticeSendReq) (*v1.NoticeSendResp, error) {
	l := logic.NewSendLogic(ctx, s.svcCtx)
	return l.Send(in)
}

func (s *NoticeServer) Alert(ctx context.Context, in *v1.AlertSendReq) (*v1.AlertSendResp, error) {
	l := logic.NewAlertLogic(ctx, s.svcCtx)
	return l.Alert(in)
}
