// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/shopspring/decimal"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	coinPricesFieldNames          = builder.RawFieldNames(&CoinPrices{})
	coinPricesRows                = strings.Join(coinPricesFieldNames, ",")
	coinPricesRowsExpectAutoSet   = strings.Join(stringx.Remove(coinPricesFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	coinPricesRowsWithPlaceHolder = strings.Join(stringx.Remove(coinPricesFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheCoinPricesIdPrefix = "cache:coinPrices:id:"
)

type (
	coinPricesModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *CoinPrices) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CoinPrices, error)
		Update(ctx context.Context, session sqlx.Session, data *CoinPrices) (sql.Result, error)
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultCoinPricesModel struct {
		sqlc.CachedConn
		table string
	}

	CoinPrices struct {
		Id int64 `db:"id"`

		CoinUnit string `db:"coin_unit"` // 币种

		Price decimal.Decimal `db:"price"` // 日出价格

		DateTime time.Time `db:"date_time"` // 日期

		Created time.Time `db:"created"` // 创建时间

		Updated time.Time `db:"updated"` // 最近更新时间

	}
)

func newCoinPricesModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultCoinPricesModel {
	return &defaultCoinPricesModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`coin_prices`",
	}
}

func (m *defaultCoinPricesModel) Insert(ctx context.Context, session sqlx.Session, data *CoinPrices) (sql.Result, error) {
	coinPricesIdKey := fmt.Sprintf("%s%v", cacheCoinPricesIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, coinPricesRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.CoinUnit, data.Price, data.DateTime, data.Created, data.Updated)
		}
		return conn.ExecCtx(ctx, query, data.CoinUnit, data.Price, data.DateTime, data.Created, data.Updated)
	}, coinPricesIdKey)
}

func (m *defaultCoinPricesModel) FindOne(ctx context.Context, id int64) (*CoinPrices, error) {
	coinPricesIdKey := fmt.Sprintf("%s%v", cacheCoinPricesIdPrefix, id)
	var resp CoinPrices
	err := m.QueryRowCtx(ctx, &resp, coinPricesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", coinPricesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCoinPricesModel) Update(ctx context.Context, session sqlx.Session, data *CoinPrices) (sql.Result, error) {
	coinPricesIdKey := fmt.Sprintf("%s%v", cacheCoinPricesIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, coinPricesRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.CoinUnit, data.Price, data.DateTime, data.Created, data.Updated, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.CoinUnit, data.Price, data.DateTime, data.Created, data.Updated, data.Id)
	}, coinPricesIdKey)
}

func (m *defaultCoinPricesModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	coinPricesIdKey := fmt.Sprintf("%s%v", cacheCoinPricesIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, coinPricesIdKey)
	return err
}

func (m *defaultCoinPricesModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheCoinPricesIdPrefix, primary)
}
func (m *defaultCoinPricesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", coinPricesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCoinPricesModel) tableName() string {
	return m.table
}
