// Code generated by goctl. DO NOT EDIT!
// Source: notice.proto

package server

import (
	"market_server/app/admin/rpc/internal/logic"
	"market_server/app/admin/rpc/internal/svc"
	pb2 "market_server/app/admin/rpc/types/pb"
	"context"
)

type NoticeServer struct {
	svcCtx *svc.ServiceContext
	pb2.UnimplementedNoticeServer
}

func NewNoticeServer(svcCtx *svc.ServiceContext) *NoticeServer {
	return &NoticeServer{
		svcCtx: svcCtx,
	}
}

func (s *NoticeServer) GetWebsocketUrl(ctx context.Context, in *pb2.GetWebsocketUrlReq) (*pb2.GetWebsocketUrlRsp, error) {
	l := logic.NewGetWebsocketUrlLogic(ctx, s.svcCtx)
	return l.GetWebsocketUrl(in)
}
