// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	comm "bcts/app/client/api/internal/handler/comm"
	order "bcts/app/client/api/internal/handler/order"
	user "bcts/app/client/api/internal/handler/user"
	"bcts/app/client/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/info",
				Handler: user.GetUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/settlement/info",
				Handler: user.GetUserSettlementInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/account/info",
				Handler: user.GetAccountInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/add",
				Handler: user.AddTestHandler(serverCtx),
			},
		},
		rest.WithPrefix("/trading/api/v2"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/comm/currency/info",
				Handler: comm.GetCurrencyInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/comm/symbol/info",
				Handler: comm.GetSymbolInfoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/trading/api/v2"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/otc-quote",
				Handler: order.OtcQuoteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/create-order",
				Handler: order.CreateOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/otc-order",
				Handler: order.GetOTCOrderHandler(serverCtx),
			},
		},
		rest.WithPrefix("/trading/api/v2"),
	)
}
