// Code generated by goctl. DO NOT EDIT!
// Source: pms.proto

package server

import (
	"context"

	"bcts/app/pms/rpc/internal/logic"
	"bcts/app/pms/rpc/internal/svc"
	"bcts/app/pms/rpc/types/pb"
)

type PmsServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedPmsServer
}

func NewPmsServer(svcCtx *svc.ServiceContext) *PmsServer {
	return &PmsServer{
		svcCtx: svcCtx,
	}
}

func (s *PmsServer) CreatePortfolioInvestment(ctx context.Context, in *pb.CreatePortfolioInvestmentReq) (*pb.EmptyRsp, error) {
	l := logic.NewCreatePortfolioInvestmentLogic(ctx, s.svcCtx)
	return l.CreatePortfolioInvestment(in)
}

func (s *PmsServer) DeletePortfolioInvestment(ctx context.Context, in *pb.DeletePortfolioInvestmentReq) (*pb.EmptyRsp, error) {
	l := logic.NewDeletePortfolioInvestmentLogic(ctx, s.svcCtx)
	return l.DeletePortfolioInvestment(in)
}

func (s *PmsServer) UpdatePortfolioInvestment(ctx context.Context, in *pb.UpdatePortfolioInvestmentReq) (*pb.EmptyRsp, error) {
	l := logic.NewUpdatePortfolioInvestmentLogic(ctx, s.svcCtx)
	return l.UpdatePortfolioInvestment(in)
}

func (s *PmsServer) GetPortfolioInvestmentList(ctx context.Context, in *pb.PortfolioInvestmentListReq) (*pb.PortfolioInvestmentListRsp, error) {
	l := logic.NewGetPortfolioInvestmentListLogic(ctx, s.svcCtx)
	return l.GetPortfolioInvestmentList(in)
}

//  资产列表
func (s *PmsServer) GetAccountAnalysis(ctx context.Context, in *pb.AccountAnalysisReq) (*pb.AccountAnalysisRsp, error) {
	l := logic.NewGetAccountAnalysisLogic(ctx, s.svcCtx)
	return l.GetAccountAnalysis(in)
}

//  资产收益率
func (s *PmsServer) GetPortfolioPerformance(ctx context.Context, in *pb.PortfolioPerformanceReq) (*pb.PortfolioPerformanceRsp, error) {
	l := logic.NewGetPortfolioPerformanceLogic(ctx, s.svcCtx)
	return l.GetPortfolioPerformance(in)
}
