// Code generated by goctl. DO NOT EDIT!
// Source: mpu.proto

package server

import (
	"context"

	"exterior-interactor/app/mpu/rpc/internal/logic"
	"exterior-interactor/app/mpu/rpc/internal/svc"
	"exterior-interactor/app/mpu/rpc/mpupb"
)

type MpuServer struct {
	svcCtx *svc.ServiceContext
	mpupb.UnimplementedMpuServer
}

func NewMpuServer(svcCtx *svc.ServiceContext) *MpuServer {
	return &MpuServer{
		svcCtx: svcCtx,
	}
}

func (s *MpuServer) GetAllSymbols(ctx context.Context, in *mpupb.EmptyReq) (*mpupb.GetAllSymbolsRsp, error) {
	l := logic.NewGetAllSymbolsLogic(ctx, s.svcCtx)
	return l.GetAllSymbols(in)
}

func (s *MpuServer) GetSymbol(ctx context.Context, in *mpupb.GetSymbolReq) (*mpupb.GetSymbolRsp, error) {
	l := logic.NewGetSymbolLogic(ctx, s.svcCtx)
	return l.GetSymbol(in)
}
