// Code generated by goctl. DO NOT EDIT.
package types

type UserInfoReq struct {
	UserID int64 `form:"user_id,optional"`
}

type UserInfoRsp struct {
	UserID   int64  `json:"user_id"`
	UserType int64  `json:"user_type"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Mobile   string `json:"mobile"`
	KycLevel int64  `json:"kyc_level"`
}

type UserSettlementInfoReq struct {
	UserID int64 `form:"user_id,optional"`
}

type SettlementInfo struct {
	BankName           string `json:"bank_name"`
	BankAccountNo      string `json:"bank_account_no"` //银行账号
	Swift              string `json:"swift"`
	RouteCode          string `json:"route_code"`
	BeneficiaryName    string `json:"beneficiary_name"`
	BeneficiaryAccount string `json:"beneficiary_account"`
	BeneficiaryAddress string `json:"beneficiary_address"`
}

type UserSettlementInfoRsp struct {
	Count int               `json:"count"`
	List  []*SettlementInfo `json:"list"`
}

type AccountInfoReq struct {
	UserID   int64  `form:"user_id,optional"`
	Currency string `form:"currency,optional"`
}

type AccountInfo struct {
	UserID    int64  `json:"user_id"`
	Currency  string `json:"currency"`
	Available string `json:"available"`
	Frozen    string `json:"frozen"`
	Balance   string `json:"balance"`
	CostPrice string `json:"cost_price"`
}

type AccountInfoRsp struct {
	Count int            `json:"count"`
	List  []*AccountInfo `json:"list"`
}

type TestAddReq struct {
	Test1 string `json:"test1"`
	Test2 string `json:"test2"`
}

type TestAddRsp struct {
	ID string `json:"id"`
}

type SymbolInfoReq struct {
	Symbol string `form:"symbol,optional"`
}

type SymbolInfo struct {
	SymbolID             string `json:"symbol_id"`               //品种代码，如 BTC_USDT
	SymbolKind           int    `json:"symbol_kind"`             //品种类型，如 1-现货、2-期货等
	Underlying           string `json:"underlying"`              //标的，如 BTC
	PrimaryCurrency      string `json:"primary_currency"`        //基础货币，如 USDT
	BidCurrency          string `json:"bid_currency"`            //报价货币，如 USDT
	SettleCurrency       string `json:"settle_currency"`         //结算货币，如 USDT
	Switch               bool   `json:"switch"`                  //交易开关
	VolumePrecision      int    `json:"volume_precision"`        //数量精度
	PricePrecision       int    `json:"price_precision"`         //价格精度
	AmountPrecision      int    `json:"amount_precision"`        //金额精度
	MinUnit              string `json:"min_unit"`                //最小交易单位
	MinChangePrice       string `json:"min_change_price"`        //最小变动价位
	Spread               string `json:"spread"`                  //点差，品种tick值的整数倍
	FeeKind              int    `json:"fee_kind"`                //手续费算法，取值1或2，1表示百比分，2表示绝对值。默认为1.
	TakerFee             string `json:"taker_fee"`               //Taker手续费率
	MakerFee             string `json:"maker_fee"`               //Maker手续费率
	SingleMinOrderVolume string `json:"single_min_order_volume"` //单次最小下单量
	SingleMaxOrderVolume string `json:"single_max_order_volume"` //单次最大下单量
	SingleMinOrderAmount string `json:"single_min_order_amount"` //单次最小下单金额
	SingleMaxOrderAmount string `json:"single_max_order_amount"` //单次最大下单金额
	BuyPriceLimit        string `json:"buy_price_limit"`         //买委托价格限制
	SellPriceLimit       string `json:"sell_price_limit"`        //卖委托价格限制
	MaxMatchGear         int    `json:"max_match_gear"`          //最大成交档位,不得超过20
	OtcMinOrderVolume    string `json:"otc_min_order_volume"`    //OTC最小量
	OtcMaxOrderVolume    string `json:"otc_max_order_volume"`    //OTC最大量
	OtcMinOrderAmount    string `json:"otc_min_order_amount"`    //OTC最小金额
	OtcMaxOrderAmount    string `json:"otc_max_order_amount"`    //OTC最大金额
}

type SymbolInfoRsp struct {
	Count int           `json:"count"`
	List  []*SymbolInfo `json:"list"`
}

type CurrencyInfoReq struct {
	Currency string `form:"currency,optional"`
}

type CurrencyInfo struct {
	CurrencyID     string `json:"currency_id"`      //币种代码，如 USDT
	Kind           int    `json:"kind"`             //币种类型，1:法币 2: 公链数字货币 3：稳定币
	ChineseName    string `json:"chinese_name"`     //中文名称，如 泰达币
	EnglishName    string `json:"english_name"`     //英文名称，如 Tether USD
	MinUnit        string `json:"min_unit"`         //币种最小单位
	DepositSwitch  bool   `json:"deposit_switch"`   //充值开关
	WithdrawSwitch bool   `json:"withdraw_switch"`  //提现开关
	MinWithdraw    string `json:"min_withdraw"`     //单笔最小提现金额
	MaxWithdraw    string `json:"max_withdraw"`     //单笔最大提现金额
	MaxDayWithdraw string `json:"max_day_withdraw"` //当日最大提现金额
	Threshold      string `json:"threshold"`        //大额提现阈值
	FeeKind        int    `json:"fee_kind"`         //提现手续费算法 1:百比分，2:绝对值。默认为1.
	Fee            string `json:"fee"`              //提现手续费率
}

type CurrencyInfoRsp struct {
	Count int             `json:"count"`
	List  []*CurrencyInfo `json:"list"`
}

type CreateOrderReq struct {
	RequestID      string `json:"request_id"`                    //请求id，区别每次请求
	UserID         int64  `json:"order_id"`                      //订单id 用户订单id，用于程序化交易
	OrderType      int32  `json:"order_type, options=1|2"`       //订单类型 1:otc订单 2:聚合交易订单
	OrderMode      int32  `json:"otc_order_mode, options=1|2"`   //下单模式 1:数量下单 2:金额下单
	OrderPriceType int32  `json:"order_price_type, options=1|2"` //报单价格条件 1:限价单 2:市价单
	Symbol         string `json:"symbol"`                        //币对
	Direction      int32  `json:"direction, options=1|2"`        //下单方向，0表示买，1表示卖
	Price          string `json:"price"`                         //报单价格
	Volume         string `json:"volume"`                        //报单数量
	Amount         string `json:"amount"`                        //报单金额
	OrderMaker     int32  `json:"order_maker, options=1|2"`      //1: taker  2:maker
}

type CreateOrderRsp struct {
	RequestID       string `json:"request_id"`                    //请求id，区别每次请求
	OrderLocalID    string `json:"order_id"`                      //订单id 用户订单id，用于程序化交易
	UserID          int64  `json:"user_id"`                       //客户UID
	OrderType       int32  `json:"order_type"`                    //订单类型 1:otc订单 2:聚合交易订单
	OrderMode       int32  `json:"otc_order_mode, options=1|2"`   //下单模式 1:数量下单 2:金额下单
	OrderPriceType  int32  `json:"order_price_type, options=1|2"` //报单价格条件 1:限价单 2:市价单
	Symbol          string `json:"symbol"`                        //币对
	Direction       int32  `json:"direction"`                     //下单方向，0或1，0表示买，1表示卖
	Price           string `json:"price"`                         //报单价格
	Volume          string `json:"volume"`                        //报单数量
	TradeVolume     string `json:"trade_volume"`                  //成交数量
	TradeAmount     string `json:"trade_amount"`                  //成交金额
	LeftoverVolume  string `json:"leftover_volume"`               //剩余量
	OrderStatus     int32  `json:"order_status"`                  //订单状态，0 已接单 "TRADING"，1 交易部分完成 / 部分匹配成交 "PART_COMPLETED"， 2 交易完成 / 已匹配成交 "COMPLETED"，3 交易取消 "CANCELED"， 4 交易部分取消 "CANCELED"
	OrderMaker      int32  `json:"order_maker"`                   //是否maker单 1:taker 2:maker
	OrderCreateTime string `json:"order_create_time"`             //订单创建时间
	OrderModifyTime string `json:"order_modify_time"`             //订单更新时间
}

type OtcQuoteReq struct {
	QuoteID   string `json:"quote_id"` //前端生成 规则 "quote_{userid}_{毫秒时间戳}"
	UserID    int64  `json:"user_id, optional"`
	Symbol    string `json:"symbol"`                  //币对，比如 BTC_USD
	Direction int32  `json:"direction,range=[0:1]"`   //下单方向 0:买，1:卖
	QuoteType int32  `json:"quote_type, options=0|1"` //询价方式 0:按数量询价 1:按金额询价
	Volume    string `json:"volume,optional"`         // 数量
	Amount    string `json:"amount,optional"`         // 交易额
}

type OtcQuoteRsp struct {
	QuoteID   string `json:"quote_id"` //前端生成 规则 "quote_{userid}_{毫秒时间戳}"
	UserID    int64  `json:"user_id"`
	Symbol    string `json:"symbol"`                  //币对
	Direction int32  `json:"direction,range=[0:1]"`   //下单方向  0:买，1:卖
	QuoteType int32  `json:"quote_type, options=0|1"` //询价方式 0:按数量询价 1:按金额询价
	Price     string `json:"price"`                   // 价格
	Volume    string `json:"volume"`                  // 数量
	Amount    string `json:"amount"`                  // 交易额
}

type OTCOrderQueryReq struct {
	Page     int `json:"page,optional,default=1"`       //页码，从1开始
	PageSize int `json:"page_size,optional,default=15"` //每页的条数
}

type OrderOrderItem struct {
	OrderLocalId    string `json:"order_local_id"`    //订单id 本地报单编号
	UserID          string `json:"user_id"`           //客户UID
	OrderType       int    `json:"order_type"`        // 订单类型 1:otc订单 2:聚合交易订单
	OrderPriceType  int    `json:"order_price_type"`  //报单价格条件 1:限价单 2:市价单
	Symbol          string `json:"symbol"`            //币对
	Direction       int    `json:"direction"`         //下单方向，0或1，0表示买，1表示卖
	Price           string `json:"price"`             //报单价格
	Volume          string `json:"volume"`            //报单数量
	Amount          string `json:"amount"`            //报单金额
	TradeVolume     string `json:"trade_volume"`      //成交数量
	TradeAmount     string `json:"trade_amount"`      //成交金额
	OrderStatus     int    `json:"order_status"`      //订单状态，0 已接单 "TRADING"，1 交易部分完成 / 部分匹配成交 "PART_COMPLETED"， 2 交易完成 / 已匹配成交 "COMPLETED"，3 交易取消 "CANCELED"， 4 交易部分取消 "CANCELED"
	OrderMaker      int    `json:"order_maker"`       //是否maker单 1:taker 2:maker
	OrderCreateTime string `json:"order_create_time"` //订单创建时间
	OrderModifyTime string `json:"order_modify_time"` //订单更新时间
}

type OrderQueryRsp struct {
	Orders []*OrderOrderItem `json:"orders"`
	Count  string            `json:"count"`
}
