// Code generated by goctl. DO NOT EDIT!
// Source: order.proto

package server

import (
	"context"

	"market_server/app/order/rpc/internal/logic"
	"market_server/app/order/rpc/internal/svc"
	"market_server/app/order/rpc/types/pb"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

// OTC询价
func (s *OrderServer) OtcQuote(ctx context.Context, in *pb.QuoteReq) (*pb.QuoteRsp, error) {
	l := logic.NewOtcQuoteLogic(ctx, s.svcCtx)
	return l.OtcQuote(in)
}

// 创建订单
func (s *OrderServer) CreateOrder(ctx context.Context, in *pb.CreateOrderReq) (*pb.CreateOrderRsp, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

// 查询订单
func (s *OrderServer) GetOTCOrder(ctx context.Context, in *pb.OTCOrderQueryReq) (*pb.OrderQueryRsp, error) {
	l := logic.NewGetOTCOrderLogic(ctx, s.svcCtx)
	return l.GetOTCOrder(in)
}
