// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: dataService.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DataServiceClient is the client API for DataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataServiceClient interface {
	//获取合约参数
	GetSymbol(ctx context.Context, in *GetSymbolReq, opts ...grpc.CallOption) (*GetSymbolRsp, error)
	//获取币种参数
	GetCurrency(ctx context.Context, in *GetCurrencyReq, opts ...grpc.CallOption) (*GetCurrencyRsp, error)
	//获取用户交易手续费
	GetUserFeeInfo(ctx context.Context, in *GetUserFeeInfoReq, opts ...grpc.CallOption) (*GetUserFeeInfoRsp, error)
	//发布参数
	PublishNacosConfig(ctx context.Context, in *PublishNacosConfig, opts ...grpc.CallOption) (*DSEmpty, error)
	//删除参数
	DeleteNacosConfig(ctx context.Context, in *DeleteNacosConfig, opts ...grpc.CallOption) (*DSEmpty, error)
}

type dataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataServiceClient(cc grpc.ClientConnInterface) DataServiceClient {
	return &dataServiceClient{cc}
}

func (c *dataServiceClient) GetSymbol(ctx context.Context, in *GetSymbolReq, opts ...grpc.CallOption) (*GetSymbolRsp, error) {
	out := new(GetSymbolRsp)
	err := c.cc.Invoke(ctx, "/pb.dataService/getSymbol", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) GetCurrency(ctx context.Context, in *GetCurrencyReq, opts ...grpc.CallOption) (*GetCurrencyRsp, error) {
	out := new(GetCurrencyRsp)
	err := c.cc.Invoke(ctx, "/pb.dataService/getCurrency", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) GetUserFeeInfo(ctx context.Context, in *GetUserFeeInfoReq, opts ...grpc.CallOption) (*GetUserFeeInfoRsp, error) {
	out := new(GetUserFeeInfoRsp)
	err := c.cc.Invoke(ctx, "/pb.dataService/getUserFeeInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) PublishNacosConfig(ctx context.Context, in *PublishNacosConfig, opts ...grpc.CallOption) (*DSEmpty, error) {
	out := new(DSEmpty)
	err := c.cc.Invoke(ctx, "/pb.dataService/publishNacosConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) DeleteNacosConfig(ctx context.Context, in *DeleteNacosConfig, opts ...grpc.CallOption) (*DSEmpty, error) {
	out := new(DSEmpty)
	err := c.cc.Invoke(ctx, "/pb.dataService/deleteNacosConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServiceServer is the server API for DataService service.
// All implementations must embed UnimplementedDataServiceServer
// for forward compatibility
type DataServiceServer interface {
	//获取合约参数
	GetSymbol(context.Context, *GetSymbolReq) (*GetSymbolRsp, error)
	//获取币种参数
	GetCurrency(context.Context, *GetCurrencyReq) (*GetCurrencyRsp, error)
	//获取用户交易手续费
	GetUserFeeInfo(context.Context, *GetUserFeeInfoReq) (*GetUserFeeInfoRsp, error)
	//发布参数
	PublishNacosConfig(context.Context, *PublishNacosConfig) (*DSEmpty, error)
	//删除参数
	DeleteNacosConfig(context.Context, *DeleteNacosConfig) (*DSEmpty, error)
	mustEmbedUnimplementedDataServiceServer()
}

// UnimplementedDataServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDataServiceServer struct {
}

func (UnimplementedDataServiceServer) GetSymbol(context.Context, *GetSymbolReq) (*GetSymbolRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSymbol not implemented")
}
func (UnimplementedDataServiceServer) GetCurrency(context.Context, *GetCurrencyReq) (*GetCurrencyRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrency not implemented")
}
func (UnimplementedDataServiceServer) GetUserFeeInfo(context.Context, *GetUserFeeInfoReq) (*GetUserFeeInfoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserFeeInfo not implemented")
}
func (UnimplementedDataServiceServer) PublishNacosConfig(context.Context, *PublishNacosConfig) (*DSEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishNacosConfig not implemented")
}
func (UnimplementedDataServiceServer) DeleteNacosConfig(context.Context, *DeleteNacosConfig) (*DSEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNacosConfig not implemented")
}
func (UnimplementedDataServiceServer) mustEmbedUnimplementedDataServiceServer() {}

// UnsafeDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataServiceServer will
// result in compilation errors.
type UnsafeDataServiceServer interface {
	mustEmbedUnimplementedDataServiceServer()
}

func RegisterDataServiceServer(s grpc.ServiceRegistrar, srv DataServiceServer) {
	s.RegisterService(&DataService_ServiceDesc, srv)
}

func _DataService_GetSymbol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSymbolReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).GetSymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.dataService/getSymbol",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).GetSymbol(ctx, req.(*GetSymbolReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_GetCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrencyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).GetCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.dataService/getCurrency",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).GetCurrency(ctx, req.(*GetCurrencyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_GetUserFeeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserFeeInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).GetUserFeeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.dataService/getUserFeeInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).GetUserFeeInfo(ctx, req.(*GetUserFeeInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_PublishNacosConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishNacosConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).PublishNacosConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.dataService/publishNacosConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).PublishNacosConfig(ctx, req.(*PublishNacosConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_DeleteNacosConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNacosConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).DeleteNacosConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.dataService/deleteNacosConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).DeleteNacosConfig(ctx, req.(*DeleteNacosConfig))
	}
	return interceptor(ctx, in, info, handler)
}

// DataService_ServiceDesc is the grpc.ServiceDesc for DataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.dataService",
	HandlerType: (*DataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getSymbol",
			Handler:    _DataService_GetSymbol_Handler,
		},
		{
			MethodName: "getCurrency",
			Handler:    _DataService_GetCurrency_Handler,
		},
		{
			MethodName: "getUserFeeInfo",
			Handler:    _DataService_GetUserFeeInfo_Handler,
		},
		{
			MethodName: "publishNacosConfig",
			Handler:    _DataService_PublishNacosConfig_Handler,
		},
		{
			MethodName: "deleteNacosConfig",
			Handler:    _DataService_DeleteNacosConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dataService.proto",
}
